env:
  browser: true
  es2021: true
extends:
  - standard
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  camelcase:
    - off
  indent:
    - error
    - 4
  comma-dangle:
    - error
    - always-multiline
