sources_by_selectors_path: config/sources_by_selectors.json
json_path: output/notices.json
save_for: 90

ding:
  secrets_path: config/ding.secrets.yaml

rss:
  title: BulletinIT
  description: Bulletin Issues Transferred
  link: https://haobit.top/dev/notices/
  rss_href: https://haobit.top/dev/notices/feed.rss
  output_path: output/feed.rss

proxy:
  secrets_path: config/proxy.secrets.yaml
  match:
    # spell-checker: disable
    - century.bit.edu.cn
    - cxcy.bit.edu.cn
    - dekt.bit.edu.cn
    - dzb.bit.edu.cn
    - mec.bit.edu.cn
    - student.bit.edu.cn
    # spell-checker: enable
